// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg7ZsRbg0o5HJ7S5LVEwNQaYciEl-hmEY',
    appId: '1:659234851207:web:04ea61ec5ba0429943eb22',
    messagingSenderId: '659234851207',
    projectId: 'zynkup-app',
    authDomain: 'zynkup-app.firebaseapp.com',
    storageBucket: 'zynkup-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7c7urdp1ICDgJkX5IE3sAfGWspiRd62s',
    appId: '1:659234851207:android:a5c4d2ea4faf3a5a43eb22',
    messagingSenderId: '659234851207',
    projectId: 'zynkup-app',
    storageBucket: 'zynkup-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHg9kKP46e0GvgVazUxOqcu6pdCxT8tcc',
    appId: '1:659234851207:ios:3fdcd4af05367b7543eb22',
    messagingSenderId: '659234851207',
    projectId: 'zynkup-app',
    storageBucket: 'zynkup-app.firebasestorage.app',
    androidClientId: '659234851207-tn1bsia4vtdtavh2gi4q9k9ch4t9u1gs.apps.googleusercontent.com',
    iosClientId: '659234851207-fl9gfob5pr92m2gkjn0rthpboftgvtun.apps.googleusercontent.com',
    iosBundleId: 'com.example.zynkup',
  );

}