class DelhiColleges {
  static const List<String> list = [
    'Maharaja Agrasen Institute of Technology (MAIT)',
    'Maharaja Surajmal Institute of Technology (MSIT)',
    'Delhi Technological University (DTU)',
    'Netaji Subhas University of Technology (NSUT)',
    'Indian Institute of Technology Delhi (IIT Delhi)',
    'Indraprastha Institute of Information Technology Delhi (IIIT-Delhi)',
    'Indira Gandhi Delhi Technical University for Women (IGDTUW)',
    'Bharati Vidyapeeth\'s College of Engineering (BVCOE)',
    'Bhagwan Parshuram Institute of Technology (BPIT)',
    'Guru Gobind Singh Indraprastha University (GGSIPU Main Campus)',
    'Dr. Akhilesh Das Gupta Institute of Technology & Management (ADGITM)',
    'HMR Institute of Technology & Management (HMRITM)',
    'Vivekananda Institute of Professional Studies (VIPS)',
    'Jagan Institute of Management Studies (JIMS Rohini)',
    'Trinity Institute of Professional Studies (TIPS)',
    'Delhi Skill and Entrepreneurship University (DSEU)',
    'Jawaharlal Nehru University (JNU)',
    'Jamia Millia Islamia (JMI)',
    'Jamia Hamdard',
    'Dr. B.R. Ambedkar University Delhi (AUD)',
    'National Law University Delhi (NLU Delhi)',
    'All India Institute of Medical Sciences (AIIMS Delhi)',
    'Maulana Azad Medical College (MAMC)',
    'Vardhman Mahavir Medical College (VMMC)',
    'University College of Medical Sciences (UCMS)',
    'Lady Hardinge Medical College (LHMC)',
    'St. Stephen\'s College (DU)',
    'Shri Ram College of Commerce (SRCC, DU)',
    'Hindu College (DU)',
    'Hansraj College (DU)',
    'Miranda House (DU)',
    'Lady Shri Ram College for Women (LSR, DU)',
    'Sri Venkateswara College (Venky, DU)',
    'Kirori Mal College (KMC, DU)',
    'Ramjas College (DU)',
    'Atma Ram Sanatan Dharma College (ARSD, DU)',
    'Gargi College (DU)',
    'Jesus and Mary College (JMC, DU)',
    'Kamala Nehru College (DU)',
    'Maitreyi College (DU)',
    'Shaheed Bhagat Singh College (SBSC, DU)',
    'Shaheed Sukhdev College of Business Studies (SSCBS, DU)',
    'Dyal Singh College (DU)',
    'Deshbandhu College (DU)',
    'Acharya Narendra Dev College (ANDC, DU)',
    'Keshav Mahavidyalaya (DU)',
    'Deen Dayal Upadhyaya College (DDUC, DU)',
    'Motilal Nehru College (DU)',
    'Rajdhani College (DU)',
    'Shivaji College (DU)',
    'Satyawati College (DU)',
    'Zakir Husain Delhi College (DU)',
    'College of Vocational Studies (CVS, DU)',
    'Delhi School of Economics (DSE, DU)',
    'Faculty of Management Studies (FMS, DU)',
    'National Institute of Fashion Technology Delhi (NIFT Delhi)',
    'Indian Institute of Foreign Trade (IIFT Delhi)',
    'Lal Bahadur Shastri Institute of Management (LBSIM)',
    'Delhi Pharmaceutical Sciences and Research University (DPSRU)',
    'Other / Outside Delhi',
  ];
}
